stages:
  - satis-update
trigger_build:
  stage: satis-update
  script:
    - "curl -X POST -F token=1c61dddc8b2ba95cbae282752afec8 -F ref=master https://gitlab.oms.systems/api/v4/projects/60/trigger/pipeline"